config/routes.rb
Rails.application.routes.draw do
  get 'likes/toggle'
  resources :posts
  devise_for :users

   devise_scope :user do
  authenticated :user do
    root 'posts#index', as: :authenticated_root
  end

  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end
end


  post 'image/create', to: 'images#create', as: :images
  post 'comment/create', to: 'comments#create', as: :comments

  delete 'comments/:id', to: 'comments#destroy', as: :comments_delete

  delete 'images/:id', to: 'images#destroy', as: :images_delete

    post 'likes/toggle/:post_id', to: 'likes#toggle', as: :toggle_like


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord

	belongs_to :user
	has_many :images
	has_many :comments
	has_many :likes

	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
 validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

 	def user_can_like(user_id)

 		if self.likes.where(user_id: user_id).length >0

 			return false

 		else
 			return true

 		end



 	end

 	def user_like_string(user_id)

 		if self.user_can_like(user_id)
 			return 'Like'

 		else
 			return 'Unlike'
 		end

 	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    @post = Post.new
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @image = Image.new
    @abc = Image.all
    @comment = Comment.new
    @comments = Comment.all
  end

  # GET /posts/new
  def new
    @post = Post.new
    
    
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    
    @post = Post.new(post_params);
    @comment = Comment.new;
    @post.user_id = current_user.id;


    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:content, :title, :avatar)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1 class="edit-post-style">Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<header>
<nav>
<ul id = "horizontal-list">
  <li>ABOUT</li>
  <li>CONTACT US</li>
  <li>LINKS</li>
  <li>PRIVACY POLICY</li>
  <li>ADVERTISE</li>
</ul>
</nav>
</header>

<main id = "posts-index">
<p id="notice"><%= notice %></p>

<h1>Posts</h1>
<% if user_signed_in? ==false%>
<%=link_to 'Sign-in', '/users/sign_in', class:"sign-in-post-style" %>
<% end %>

  
   <!--  <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr> -->
 

  <div id = "material">
    <% @posts.each do |post| %>
      
        <div id = "post-title-style">
        <%= post.title %>--- <%= post.user.email %>
        
        <div>
          <%= image_tag post.avatar.url, id:"image-title-style" %>
        </div>
        <br>
        <div id = "material-links">
        <%= link_to 'Show', post, class: 'edit-link'  %>
        <% if user_signed_in? %>
        <% if current_user.id == post.user_id %>
        <%= link_to 'Edit', edit_post_path(post),class: 'edit-link' %>
        <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' },class: 'edit-link' %>
        <% end %>
        <% end %>
        </div>
        </div>
        <%= post.likes.length %>
        <%= link_to post.user_like_string(current_user.id), toggle_like_path(post), method: :post %>
    
    <% end %>

  </div>
  


<br>
<% if user_signed_in? %>
<%= link_to 'New Post', new_post_path, class: "sign-in-post-style" %>
<% end %>
</main>

app/views/posts/new.html.erb
<h1 class = "new-post-style">New Post</h1>

<%=form_for @post, html: { multipart: true } do |f| %>

	<%= f.label :title, class: "new-post-style" %>
	<%= f.text_area :title %>

	<br>
	<%= f.label :content, class: "new-post-style" %>
	<%= f.text_area :content %>

	<br>

	<%= f.label :image %>
	<%= f.file_field :avatar %>

	<%= f.submit %>
	<% end %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div id = "paragh-content">
<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

</div>
	<% if user_signed_in? %>
	<% if current_user.id == @post.user_id %>
	<div>
		
			<%= form_for @image,html: { multipart: true }, remote:false do |f| %>

				<%= f.label :image %>
				<%= f.file_field :avatar %>

				<%= f.hidden_field :post_id, value: @post.id%>

				<%= f.submit %>

				<% end %>

	</div>
	<% end %>
	<% end %>
	
	<div id = "image-parent-style">

		<% @post.images.each do |img| %>
  		<%= image_tag img.avatar.url, id:"image-style" %>
  		<% if user_signed_in? %>
		<% if current_user.id == @post.user_id %>
  		<%= link_to "image-delete", images_delete_path(img), method: :delete %>
  		<% end %>
  		<% end %>
		<% end %>
		

	</div>

	<div id = "comment-style">
	
			<%= form_for @comment do |f| %>

				<%= f.label :content %>
				<%= f.text_field :content %>

				<%= f.hidden_field :post_id, value: @post.id %>
				<%= f.submit %>
			<% end %>

	
	
	</div>

	

	<div id = "comment-list-style">
		<div id = "comment-heading-style">
			<p> Comments </p>
		</div>

		<% @post.comments.reverse.each do |comment| %>
		
		<%= comment.content %>----<%= comment.user.email %>
		<% if user_signed_in? %>
		<% if current_user.id == @post.user_id %>
		<%= link_to "delete", comments_delete_path(comment), method: :delete %>
		<% end %>
		<% end %>
		<br>
		<% end %>

		

		

	</div>






<div>
	<% if user_signed_in? %>
<% if current_user.id == @post.user_id %>
<%= link_to 'Edit', edit_post_path(@post),class: "show-tags" %> 
<% end %>
<% end %>

<%= link_to 'Back', posts_path,class: "show-tags" %>
</div>